name: Run tests

on:
  push:
    pull_request:

jobs:
  test:
    runs-on: dgellow/idris:v1.3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: idris --testpkg anagram.ipkg
