name: Run tests

on:
  push:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: mmhelloworld/idris:1.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: idris --testpkg anagram.ipkg
